# Generated by Django 5.2 on 2025-04-06 17:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('symbolism', models.TextField(max_length=1000)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracklist.flower')),
            ],
        ),
    ]
